---
title: "Flex Youtube"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
---

```{r setup, include=FALSE}
# Settingan Agar tidak muncul numeric value
options(scipen = 9999)

# List Library
library(tidyverse)
library(scales)
library(flexdashboard)
library(plotly)
library(glue)

# Data
vids <- read_csv("data_input/youtubetrends.csv")

# Data Cleansing
vids_clean <- vids %>% 
  mutate(timetotrend = as.integer(timetotrend),
         category_id = as.factor(category_id),
         channel_title = as.factor(channel_title),
         publish_hour = as.factor(publish_hour),
         publish_when = as.factor(publish_when),
         publish_wday = as.factor(publish_wday)) %>% 
  mutate(likes_per_view = likes / views,
         dislikes_per_view = dislikes / views,
         comment_per_view = comment_count / views)
```

Column {data-width=500}
-----------------------------------------------------------------------

### Plot 1

```{r}
# Prosesing data untuk plot 1
vids_count <- 
vids_clean %>% 
  group_by(category_id) %>% 
  summarise(freq = n()) %>% 
  arrange(-freq) %>% 
  mutate(label = glue("Category: {category_id}
                      Freq: {freq}"))

# Pembuatan visual statis
plot1 <- 
ggplot(data = vids_count, mapping = aes(x = freq, 
                                        y = reorder(category_id, freq),
                                        text = label)) +
  geom_col(mapping = aes(fill = freq)) +
  scale_fill_gradient(low = "red", high = "black") +
    labs(title = 'Trending Categories on Youtube US 2017' ,
       x = 'Video Count',
       y = NULL) +
  theme_minimal() +
  theme(legend.position = "none") 

# Visual interaktif kita

ggplotly(plot1, tooltip = "text")
```


Column {data-width=500}
-----------------------------------------------------------------------

### Plot 2

```{r}
# Persiapan data
vids_top_channel <- 
vids_clean %>% 
  filter(category_id %in% "Education") %>% 
  group_by(channel_title) %>% 
  summarise(mean_views = mean(views)) %>% 
  arrange(-mean_views) %>% 
  head(10) %>% 
  mutate(label = glue("Channel Title: {channel_title}
                      Mean Views: {scales::comma(mean_views)}"))

# Pembuatan visual
plot2 <- 
ggplot(data = vids_top_channel, mapping = aes(x = mean_views, 
                                              y = channel_title,
                                              color = mean_views,
                                              text = label)) +
  geom_segment(mapping = aes(x = 0, xend = mean_views, 
                             y = reorder(channel_title, mean_views), yend = channel_title)) +
  geom_point() +
  scale_color_gradient(low = "red", high = "black") +
  scale_x_continuous(labels = label_number(big.mark = ".")) +
  labs(x = 'Mean Views',
       y = NULL,
       title = 'Top 10 YouTube Channels in Entertainment') +
  theme_minimal() +
  theme(legend.position = "none") 

# Pembuatan visual interaktif
ggplotly(p = plot2, tooltip = "text")
```

### Chart C

```{r}
# Persiapan data
vids_trend <- 
vids_clean %>% 
  filter(category_id %in% "Entertainment") %>% 
  group_by(publish_hour) %>% 
  summarise(mean_views = mean(views)) %>% 
  mutate(label = glue("Hour: {publish_hour}
                      Views: {scales::comma(mean_views, accuracy = 0.01)}"))

# Visual Statis
plot3 <- 
ggplot(data = vids_trend, mapping = aes(x = as.factor(publish_hour), 
                                        y = mean_views, 
                                        text = label))+
  geom_line(group = 1, color = "red") +
  geom_point() +
    scale_y_continuous(labels = scales::comma) +
  labs(title = "Viewers Activity for Entertainment Videos",
       x = "Publish Hour",
       y = "Average Views") +
  theme_minimal()

# Visual interaktif
ggplotly(p = plot3, tooltip = "text")
```







